// =====================================================================================
// RBAC catalogue — the source of truth for permissions and system roles.
//
// Converted once from the previous stack's reviewed SQL and maintained here since; the
// converter has been removed rather than left to rot. The role mappings encode
// segregation of duties:
// the officer who prepares payroll cannot approve it, the accountant who raises a
// journal cannot post it, and a teacher reaches no payroll, ledger, health or
// counselling permission. A permission being ABSENT from a role is a decision.
//
// 142 permissions · 26 roles · 360 grants
// =====================================================================================

export interface PermissionSeed {
  code: string;
  module: string;
  description: string;
  isSensitive: boolean;
  isChildSensitive: boolean;
}

export interface RoleSeed {
  code: string;
  name: string;
  description: string;
  scope: 'PLATFORM' | 'SCHOOL';
  permissions: string[];
}

export const PERMISSIONS: PermissionSeed[] = [
  { code: 'PLATFORM_TENANT_VIEW', module: 'platform', description: 'Platform tenant view', isSensitive: false, isChildSensitive: false },
  { code: 'PLATFORM_TENANT_PROVISION', module: 'platform', description: 'Platform tenant provision', isSensitive: false, isChildSensitive: false },
  { code: 'PLATFORM_TENANT_SUSPEND', module: 'platform', description: 'Platform tenant suspend', isSensitive: true, isChildSensitive: false },
  { code: 'PLATFORM_SUBSCRIPTION_MANAGE', module: 'platform', description: 'Platform subscription manage', isSensitive: false, isChildSensitive: false },
  { code: 'PLATFORM_HEALTH_VIEW', module: 'platform', description: 'Platform health view', isSensitive: false, isChildSensitive: false },
  { code: 'PLATFORM_SUPPORT_REQUEST_ACCESS', module: 'platform', description: 'Request time-boxed support access to a tenant', isSensitive: false, isChildSensitive: false },
  { code: 'PLATFORM_SUPPORT_APPROVE_ACCESS', module: 'platform', description: 'Approve a support access request', isSensitive: true, isChildSensitive: false },
  { code: 'PLATFORM_AUDIT_VIEW', module: 'platform', description: 'Platform audit view', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_SETTINGS_VIEW', module: 'tenant_settings', description: 'Tenant settings view', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_SETTINGS_MANAGE', module: 'tenant_settings', description: 'Tenant settings manage', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_BRANDING_MANAGE', module: 'tenant_settings', description: 'Tenant branding manage', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_CAMPUS_MANAGE', module: 'tenant_settings', description: 'Tenant campus manage', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_INTEGRATION_MANAGE', module: 'tenant_settings', description: 'Tenant integration manage', isSensitive: false, isChildSensitive: false },
  { code: 'TENANT_API_KEY_MANAGE', module: 'tenant_settings', description: 'Tenant api key manage', isSensitive: true, isChildSensitive: false },
  { code: 'TENANT_RETENTION_MANAGE', module: 'tenant_settings', description: 'Tenant retention manage', isSensitive: true, isChildSensitive: false },
  { code: 'USER_VIEW', module: 'identity_and_access', description: 'User view', isSensitive: false, isChildSensitive: false },
  { code: 'USER_INVITE', module: 'identity_and_access', description: 'User invite', isSensitive: false, isChildSensitive: false },
  { code: 'USER_SUSPEND', module: 'identity_and_access', description: 'User suspend', isSensitive: false, isChildSensitive: false },
  { code: 'ROLE_VIEW', module: 'identity_and_access', description: 'Role view', isSensitive: false, isChildSensitive: false },
  { code: 'ROLE_MANAGE', module: 'identity_and_access', description: 'Role manage', isSensitive: true, isChildSensitive: false },
  { code: 'PERMISSION_ASSIGN', module: 'identity_and_access', description: 'Permission assign', isSensitive: true, isChildSensitive: false },
  { code: 'SESSION_REVOKE', module: 'identity_and_access', description: 'Session revoke', isSensitive: true, isChildSensitive: false },
  { code: 'ACADEMIC_YEAR_VIEW', module: 'academic_structure', description: 'Academic year view', isSensitive: false, isChildSensitive: false },
  { code: 'ACADEMIC_YEAR_MANAGE', module: 'academic_structure', description: 'Academic year manage', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_READ', module: 'students', description: 'Student read', isSensitive: false, isChildSensitive: true },
  { code: 'STUDENT_DELETE', module: 'students', description: 'Student delete', isSensitive: true, isChildSensitive: true },
  { code: 'STUDENT_STATUS_CHANGE', module: 'students', description: 'Student status change', isSensitive: true, isChildSensitive: true },
  { code: 'GUARDIAN_READ', module: 'students', description: 'Guardian read', isSensitive: false, isChildSensitive: true },
  { code: 'GUARDIAN_CREATE', module: 'students', description: 'Guardian create', isSensitive: false, isChildSensitive: true },
  { code: 'GUARDIAN_UPDATE', module: 'students', description: 'Guardian update', isSensitive: false, isChildSensitive: true },
  { code: 'GUARDIAN_DELETE', module: 'students', description: 'Guardian delete', isSensitive: true, isChildSensitive: true },
  { code: 'ENROLMENT_READ', module: 'students', description: 'Enrolment read', isSensitive: false, isChildSensitive: true },
  { code: 'ENROLMENT_CREATE', module: 'students', description: 'Enrolment create', isSensitive: false, isChildSensitive: true },
  { code: 'ENROLMENT_UPDATE', module: 'students', description: 'Enrolment update', isSensitive: false, isChildSensitive: true },
  { code: 'ENROLMENT_DELETE', module: 'students', description: 'Enrolment delete', isSensitive: true, isChildSensitive: true },
  { code: 'ENROLMENT_STATUS_CHANGE', module: 'students', description: 'Enrolment status change', isSensitive: true, isChildSensitive: true },
  { code: 'CLASS_VIEW', module: 'academic_structure', description: 'Class view', isSensitive: false, isChildSensitive: false },
  { code: 'CLASS_MANAGE', module: 'academic_structure', description: 'Class manage', isSensitive: false, isChildSensitive: false },
  { code: 'SUBJECT_VIEW', module: 'academic_structure', description: 'Subject view', isSensitive: false, isChildSensitive: false },
  { code: 'SUBJECT_MANAGE', module: 'academic_structure', description: 'Subject manage', isSensitive: false, isChildSensitive: false },
  { code: 'TEACHING_ASSIGNMENT_MANAGE', module: 'academic_structure', description: 'Teaching assignment manage', isSensitive: false, isChildSensitive: false },
  { code: 'TIMETABLE_VIEW', module: 'academic_structure', description: 'Timetable view', isSensitive: false, isChildSensitive: false },
  { code: 'TIMETABLE_MANAGE', module: 'academic_structure', description: 'Timetable manage', isSensitive: false, isChildSensitive: false },
  { code: 'TIMETABLE_SUBSTITUTE', module: 'academic_structure', description: 'Timetable substitute', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_VIEW', module: 'students', description: 'Student view', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_VIEW_OWN_CLASS', module: 'students', description: 'View students in classes the holder teaches, and no others', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_CREATE', module: 'students', description: 'Student create', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_UPDATE', module: 'students', description: 'Student update', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_ARCHIVE', module: 'students', description: 'Student archive', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_PROMOTE', module: 'students', description: 'Student promote', isSensitive: false, isChildSensitive: false },
  { code: 'STUDENT_DOCUMENT_VIEW', module: 'students', description: 'Student document view', isSensitive: false, isChildSensitive: true },
  { code: 'STUDENT_DOCUMENT_MANAGE', module: 'students', description: 'Student document manage', isSensitive: false, isChildSensitive: true },
  { code: 'GUARDIAN_VIEW', module: 'students', description: 'Guardian view', isSensitive: false, isChildSensitive: false },
  { code: 'GUARDIAN_MANAGE', module: 'students', description: 'Guardian manage', isSensitive: false, isChildSensitive: false },
  { code: 'ADMISSION_APPLICATION_VIEW', module: 'admissions', description: 'Admission application view', isSensitive: false, isChildSensitive: false },
  { code: 'ADMISSION_APPLICATION_MANAGE', module: 'admissions', description: 'Admission application manage', isSensitive: false, isChildSensitive: false },
  { code: 'ADMISSION_DECIDE', module: 'admissions', description: 'Admission decide', isSensitive: false, isChildSensitive: false },
  { code: 'ADMISSION_ENROL', module: 'admissions', description: 'Admission enrol', isSensitive: false, isChildSensitive: false },
  { code: 'ATTENDANCE_VIEW', module: 'attendance', description: 'Attendance view', isSensitive: false, isChildSensitive: false },
  { code: 'ATTENDANCE_MARK', module: 'attendance', description: 'Attendance mark', isSensitive: false, isChildSensitive: false },
  { code: 'ATTENDANCE_CORRECT', module: 'attendance', description: 'Attendance correct', isSensitive: false, isChildSensitive: false },
  { code: 'ATTENDANCE_LOCK', module: 'attendance', description: 'Attendance lock', isSensitive: false, isChildSensitive: false },
  { code: 'STAFF_ATTENDANCE_VIEW', module: 'attendance', description: 'Staff attendance view', isSensitive: false, isChildSensitive: false },
  { code: 'ASSESSMENT_VIEW', module: 'assessment_and_grading', description: 'Assessment view', isSensitive: false, isChildSensitive: false },
  { code: 'ASSESSMENT_MANAGE', module: 'assessment_and_grading', description: 'Assessment manage', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_ENTER', module: 'assessment_and_grading', description: 'Grade enter', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_EDIT_DRAFT', module: 'assessment_and_grading', description: 'Grade edit draft', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_SUBMIT', module: 'assessment_and_grading', description: 'Grade submit', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_REVIEW', module: 'assessment_and_grading', description: 'Grade review', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_APPROVE', module: 'assessment_and_grading', description: 'Grade approve', isSensitive: false, isChildSensitive: false },
  { code: 'GRADE_PUBLISH', module: 'assessment_and_grading', description: 'Grade publish', isSensitive: true, isChildSensitive: false },
  { code: 'GRADE_AMEND_PUBLISHED', module: 'assessment_and_grading', description: 'Amend a published mark, creating an auditable amendment record', isSensitive: true, isChildSensitive: false },
  { code: 'GRADING_SCHEME_MANAGE', module: 'assessment_and_grading', description: 'Grading scheme manage', isSensitive: false, isChildSensitive: false },
  { code: 'REPORT_CARD_VIEW', module: 'assessment_and_grading', description: 'Report card view', isSensitive: false, isChildSensitive: false },
  { code: 'REPORT_CARD_GENERATE', module: 'assessment_and_grading', description: 'Report card generate', isSensitive: false, isChildSensitive: false },
  { code: 'TRANSCRIPT_ISSUE', module: 'assessment_and_grading', description: 'Transcript issue', isSensitive: false, isChildSensitive: false },
  { code: 'FEES_VIEW', module: 'fees_and_payments', description: 'Fees view', isSensitive: false, isChildSensitive: false },
  { code: 'FEES_STRUCTURE_MANAGE', module: 'fees_and_payments', description: 'Fees structure manage', isSensitive: false, isChildSensitive: false },
  { code: 'INVOICE_CREATE', module: 'fees_and_payments', description: 'Invoice create', isSensitive: false, isChildSensitive: false },
  { code: 'INVOICE_CANCEL', module: 'fees_and_payments', description: 'Invoice cancel', isSensitive: false, isChildSensitive: false },
  { code: 'FEES_DISCOUNT', module: 'fees_and_payments', description: 'Fees discount', isSensitive: true, isChildSensitive: false },
  { code: 'FEES_WAIVE', module: 'fees_and_payments', description: 'Fees waive', isSensitive: true, isChildSensitive: false },
  { code: 'PAYMENT_RECORD', module: 'fees_and_payments', description: 'Payment record', isSensitive: false, isChildSensitive: false },
  { code: 'PAYMENT_ALLOCATE', module: 'fees_and_payments', description: 'Payment allocate', isSensitive: false, isChildSensitive: false },
  { code: 'PAYMENT_REFUND', module: 'fees_and_payments', description: 'Payment refund', isSensitive: true, isChildSensitive: false },
  { code: 'PAYMENT_REFUND_APPROVE', module: 'fees_and_payments', description: 'Payment refund approve', isSensitive: true, isChildSensitive: false },
  { code: 'RECEIPT_ISSUE', module: 'fees_and_payments', description: 'Receipt issue', isSensitive: false, isChildSensitive: false },
  { code: 'RECONCILIATION_VIEW', module: 'fees_and_payments', description: 'Reconciliation view', isSensitive: false, isChildSensitive: false },
  { code: 'RECONCILIATION_RESOLVE', module: 'fees_and_payments', description: 'Reconciliation resolve', isSensitive: false, isChildSensitive: false },
  { code: 'ACCOUNTING_VIEW', module: 'accounting', description: 'Accounting view', isSensitive: false, isChildSensitive: false },
  { code: 'ACCOUNTING_COA_MANAGE', module: 'accounting', description: 'Accounting coa manage', isSensitive: false, isChildSensitive: false },
  { code: 'ACCOUNTING_JOURNAL_CREATE', module: 'accounting', description: 'Accounting journal create', isSensitive: false, isChildSensitive: false },
  { code: 'ACCOUNTING_JOURNAL_APPROVE', module: 'accounting', description: 'Accounting journal approve', isSensitive: true, isChildSensitive: false },
  { code: 'ACCOUNTING_JOURNAL_POST', module: 'accounting', description: 'Accounting journal post', isSensitive: true, isChildSensitive: false },
  { code: 'ACCOUNTING_JOURNAL_REVERSE', module: 'accounting', description: 'Accounting journal reverse', isSensitive: true, isChildSensitive: false },
  { code: 'ACCOUNTING_PERIOD_CLOSE', module: 'accounting', description: 'Accounting period close', isSensitive: true, isChildSensitive: false },
  { code: 'ACCOUNTING_PERIOD_REOPEN', module: 'accounting', description: 'Reopen a closed accounting period, with a recorded reason', isSensitive: true, isChildSensitive: false },
  { code: 'ACCOUNTING_REPORT_VIEW', module: 'accounting', description: 'Accounting report view', isSensitive: false, isChildSensitive: false },
  { code: 'TAX_RULE_MANAGE', module: 'accounting', description: 'Tax rule manage', isSensitive: false, isChildSensitive: false },
  { code: 'BUDGET_MANAGE', module: 'accounting', description: 'Budget manage', isSensitive: false, isChildSensitive: false },
  { code: 'HR_STAFF_VIEW', module: 'hr', description: 'Hr staff view', isSensitive: false, isChildSensitive: false },
  { code: 'HR_STAFF_MANAGE', module: 'hr', description: 'Hr staff manage', isSensitive: false, isChildSensitive: false },
  { code: 'HR_CONTRACT_MANAGE', module: 'hr', description: 'Hr contract manage', isSensitive: false, isChildSensitive: false },
  { code: 'HR_SALARY_VIEW', module: 'hr', description: 'Hr salary view', isSensitive: true, isChildSensitive: false },
  { code: 'HR_SALARY_MANAGE', module: 'hr', description: 'Hr salary manage', isSensitive: true, isChildSensitive: false },
  { code: 'HR_LEAVE_REQUEST', module: 'hr', description: 'Hr leave request', isSensitive: false, isChildSensitive: false },
  { code: 'HR_LEAVE_APPROVE', module: 'hr', description: 'Hr leave approve', isSensitive: false, isChildSensitive: false },
  { code: 'HR_PERFORMANCE_MANAGE', module: 'hr', description: 'Hr performance manage', isSensitive: false, isChildSensitive: false },
  { code: 'HR_DISCIPLINARY_MANAGE', module: 'hr', description: 'Hr disciplinary manage', isSensitive: false, isChildSensitive: false },
  { code: 'PAYROLL_VIEW', module: 'payroll', description: 'Payroll view', isSensitive: false, isChildSensitive: false },
  { code: 'PAYROLL_PREPARE', module: 'payroll', description: 'Payroll prepare', isSensitive: false, isChildSensitive: false },
  { code: 'PAYROLL_APPROVE', module: 'payroll', description: 'Payroll approve', isSensitive: true, isChildSensitive: false },
  { code: 'PAYROLL_POST', module: 'payroll', description: 'Payroll post', isSensitive: true, isChildSensitive: false },
  { code: 'PAYROLL_STATUTORY_MANAGE', module: 'payroll', description: 'Payroll statutory manage', isSensitive: true, isChildSensitive: false },
  { code: 'PAYSLIP_VIEW_OWN', module: 'payroll', description: 'View only the holder’s own payslips', isSensitive: false, isChildSensitive: false },
  { code: 'PAYSLIP_VIEW_ALL', module: 'payroll', description: 'View any employee’s payslip', isSensitive: true, isChildSensitive: false },
  { code: 'LIBRARY_VIEW', module: 'library_inventory_procurement_assets', description: 'Library view', isSensitive: false, isChildSensitive: false },
  { code: 'LIBRARY_MANAGE', module: 'library_inventory_procurement_assets', description: 'Library manage', isSensitive: false, isChildSensitive: false },
  { code: 'LIBRARY_CIRCULATE', module: 'library_inventory_procurement_assets', description: 'Library circulate', isSensitive: false, isChildSensitive: false },
  { code: 'INVENTORY_VIEW', module: 'library_inventory_procurement_assets', description: 'Inventory view', isSensitive: false, isChildSensitive: false },
  { code: 'INVENTORY_MANAGE', module: 'library_inventory_procurement_assets', description: 'Inventory manage', isSensitive: false, isChildSensitive: false },
  { code: 'INVENTORY_ADJUST', module: 'library_inventory_procurement_assets', description: 'Inventory adjust', isSensitive: true, isChildSensitive: false },
  { code: 'PROCUREMENT_REQUEST', module: 'library_inventory_procurement_assets', description: 'Procurement request', isSensitive: false, isChildSensitive: false },
  { code: 'PROCUREMENT_APPROVE', module: 'library_inventory_procurement_assets', description: 'Procurement approve', isSensitive: false, isChildSensitive: false },
  { code: 'PROCUREMENT_ORDER', module: 'library_inventory_procurement_assets', description: 'Procurement order', isSensitive: false, isChildSensitive: false },
  { code: 'PROCUREMENT_RECEIVE', module: 'library_inventory_procurement_assets', description: 'Procurement receive', isSensitive: false, isChildSensitive: false },
  { code: 'ASSET_VIEW', module: 'library_inventory_procurement_assets', description: 'Asset view', isSensitive: false, isChildSensitive: false },
  { code: 'ASSET_MANAGE', module: 'library_inventory_procurement_assets', description: 'Asset manage', isSensitive: false, isChildSensitive: false },
  { code: 'ASSET_DISPOSE', module: 'library_inventory_procurement_assets', description: 'Asset dispose', isSensitive: true, isChildSensitive: false },
  { code: 'TRANSPORT_VIEW', module: 'operations', description: 'Transport view', isSensitive: false, isChildSensitive: true },
  { code: 'TRANSPORT_MANAGE', module: 'operations', description: 'Transport manage', isSensitive: false, isChildSensitive: true },
  { code: 'HOSTEL_VIEW', module: 'operations', description: 'Hostel view', isSensitive: false, isChildSensitive: false },
  { code: 'HOSTEL_MANAGE', module: 'operations', description: 'Hostel manage', isSensitive: false, isChildSensitive: false },
  { code: 'HEALTH_RECORD_VIEW', module: 'restricted_personal_records', description: 'Health record view', isSensitive: false, isChildSensitive: true },
  { code: 'HEALTH_RECORD_MANAGE', module: 'restricted_personal_records', description: 'Health record manage', isSensitive: false, isChildSensitive: true },
  { code: 'HEALTH_ALERT_VIEW', module: 'restricted_personal_records', description: 'Health alert view', isSensitive: false, isChildSensitive: true },
  { code: 'DISCIPLINE_VIEW', module: 'restricted_personal_records', description: 'Discipline view', isSensitive: false, isChildSensitive: true },
  { code: 'DISCIPLINE_MANAGE', module: 'restricted_personal_records', description: 'Discipline manage', isSensitive: false, isChildSensitive: true },
  { code: 'COUNSELLING_VIEW', module: 'restricted_personal_records', description: 'Counselling view', isSensitive: false, isChildSensitive: true },
  { code: 'COUNSELLING_MANAGE', module: 'restricted_personal_records', description: 'Counselling manage', isSensitive: false, isChildSensitive: true },
  { code: 'ANNOUNCEMENT_VIEW', module: 'communications', description: 'Announcement view', isSensitive: false, isChildSensitive: false },
  { code: 'ANNOUNCEMENT_PUBLISH', module: 'communications', description: 'Announcement publish', isSensitive: false, isChildSensitive: false },
  { code: 'NOTIFICATION_TEMPLATE_MANAGE', module: 'communications', description: 'Notification template manage', isSensitive: false, isChildSensitive: false },
  { code: 'NOTIFICATION_SETTINGS_MANAGE', module: 'communications', description: 'Notification settings manage', isSensitive: false, isChildSensitive: false },
  { code: 'NOTIFICATION_FAILURE_VIEW', module: 'communications', description: 'Notification failure view', isSensitive: false, isChildSensitive: false },
  { code: 'SMS_SEND_BULK', module: 'communications', description: 'Send SMS to a large recipient list, subject to confirmation and quota', isSensitive: true, isChildSensitive: false },
  { code: 'MESSAGE_SEND', module: 'communications', description: 'Message send', isSensitive: false, isChildSensitive: false },
  { code: 'DASHBOARD_EXECUTIVE_VIEW', module: 'analytics_audit_data', description: 'Dashboard executive view', isSensitive: false, isChildSensitive: false },
  { code: 'ANALYTICS_FINANCE_VIEW', module: 'analytics_audit_data', description: 'Analytics finance view', isSensitive: false, isChildSensitive: false },
  { code: 'ANALYTICS_ACADEMIC_VIEW', module: 'analytics_audit_data', description: 'Analytics academic view', isSensitive: false, isChildSensitive: false },
  { code: 'AUDIT_LOG_VIEW', module: 'analytics_audit_data', description: 'Audit log view', isSensitive: true, isChildSensitive: false },
  { code: 'DATA_EXPORT', module: 'analytics_audit_data', description: 'Data export', isSensitive: true, isChildSensitive: false },
  { code: 'DATA_IMPORT', module: 'analytics_audit_data', description: 'Data import', isSensitive: false, isChildSensitive: false },
  { code: 'PRIVACY_REQUEST_HANDLE', module: 'analytics_audit_data', description: 'Privacy request handle', isSensitive: true, isChildSensitive: false },
];

export const ROLES: RoleSeed[] = [
  {
    code: 'PLATFORM_SUPER_ADMIN',
    name: 'Platform Super Admin',
    description:
      'Operates the platform itself. Deliberately holds no permission over a school’s student, health, discipline or academic records; entering a tenant requires a time-boxed, reasoned support grant.',
    scope: 'PLATFORM',
    permissions: [
      'PLATFORM_AUDIT_VIEW',
      'PLATFORM_HEALTH_VIEW',
      'PLATFORM_SUBSCRIPTION_MANAGE',
      'PLATFORM_SUPPORT_APPROVE_ACCESS',
      'PLATFORM_TENANT_PROVISION',
      'PLATFORM_TENANT_SUSPEND',
      'PLATFORM_TENANT_VIEW',
    ],
  },
  {
    code: 'PLATFORM_SUPPORT',
    name: 'Platform Support',
    description:
      'Reads platform health and may request, never self-approve, tenant access.',
    scope: 'PLATFORM',
    permissions: [
      'PLATFORM_HEALTH_VIEW',
      'PLATFORM_SUPPORT_REQUEST_ACCESS',
      'PLATFORM_TENANT_VIEW',
    ],
  },
  {
    code: 'SCHOOL_OWNER',
    name: 'School Owner',
    description:
      'Full authority within one school, including subscription and role administration.',
    scope: 'SCHOOL',
    permissions: [
      'ACCOUNTING_REPORT_VIEW',
      'ACCOUNTING_VIEW',
      'ANALYTICS_ACADEMIC_VIEW',
      'ANALYTICS_FINANCE_VIEW',
      'AUDIT_LOG_VIEW',
      'DASHBOARD_EXECUTIVE_VIEW',
      'DATA_EXPORT',
      'FEES_VIEW',
      'HR_STAFF_VIEW',
      'PAYROLL_VIEW',
      'PERMISSION_ASSIGN',
      'PRIVACY_REQUEST_HANDLE',
      'ROLE_MANAGE',
      'ROLE_VIEW',
      'SESSION_REVOKE',
      'STUDENT_VIEW',
      'STUDENT_READ',
      'STUDENT_CREATE',
      'STUDENT_UPDATE',
      'STUDENT_STATUS_CHANGE',
      'TENANT_API_KEY_MANAGE',
      'TENANT_BRANDING_MANAGE',
      'TENANT_CAMPUS_MANAGE',
      'TENANT_INTEGRATION_MANAGE',
      'TENANT_RETENTION_MANAGE',
      'TENANT_SETTINGS_MANAGE',
      'TENANT_SETTINGS_VIEW',
      'USER_INVITE',
      'USER_SUSPEND',
      'USER_VIEW',
    ],
  },
  {
    code: 'SCHOOL_ADMIN',
    name: 'School Administrator',
    description:
      'Day-to-day administration of people, structure and settings. Not finance approval, not payroll approval.',
    scope: 'SCHOOL',
    permissions: [
      'ACADEMIC_YEAR_MANAGE',
      'ACADEMIC_YEAR_VIEW',
      'ADMISSION_APPLICATION_MANAGE',
      'ADMISSION_APPLICATION_VIEW',
      'ADMISSION_ENROL',
      'ANNOUNCEMENT_PUBLISH',
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_MANAGE',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_CORRECT',
      'ATTENDANCE_LOCK',
      'ATTENDANCE_VIEW',
      'AUDIT_LOG_VIEW',
      'CLASS_MANAGE',
      'CLASS_VIEW',
      'DATA_EXPORT',
      'DATA_IMPORT',
      'GUARDIAN_MANAGE',
      'GUARDIAN_VIEW',
      'MESSAGE_SEND',
      'NOTIFICATION_FAILURE_VIEW',
      'NOTIFICATION_SETTINGS_MANAGE',
      'NOTIFICATION_TEMPLATE_MANAGE',
      'REPORT_CARD_GENERATE',
      'REPORT_CARD_VIEW',
      'ROLE_VIEW',
      'STUDENT_ARCHIVE',
      'STUDENT_CREATE',
      'STUDENT_PROMOTE',
      'STUDENT_UPDATE',
      'STUDENT_VIEW',
      'STUDENT_READ',
      'STUDENT_STATUS_CHANGE',
      'ENROLMENT_READ',
      'ENROLMENT_CREATE',
      'ENROLMENT_UPDATE',
      'ENROLMENT_STATUS_CHANGE',
      'GUARDIAN_READ',
      'GUARDIAN_CREATE',
      'GUARDIAN_UPDATE',
      'SUBJECT_MANAGE',
      'SUBJECT_VIEW',
      'TEACHING_ASSIGNMENT_MANAGE',
      'TENANT_BRANDING_MANAGE',
      'TENANT_CAMPUS_MANAGE',
      'TENANT_SETTINGS_MANAGE',
      'TENANT_SETTINGS_VIEW',
      'TIMETABLE_MANAGE',
      'TIMETABLE_SUBSTITUTE',
      'TIMETABLE_VIEW',
      'USER_INVITE',
      'USER_SUSPEND',
      'USER_VIEW',
    ],
  },
  {
    code: 'HEADMASTER',
    name: 'Headmaster / Principal',
    description:
      'Executive oversight. Reads widely and approves results; does not post journals or run payroll.',
    scope: 'SCHOOL',
    permissions: [
      'ACADEMIC_YEAR_VIEW',
      'ACCOUNTING_REPORT_VIEW',
      'ACCOUNTING_VIEW',
      'ADMISSION_APPLICATION_VIEW',
      'ADMISSION_DECIDE',
      'ANALYTICS_ACADEMIC_VIEW',
      'ANALYTICS_FINANCE_VIEW',
      'ANNOUNCEMENT_PUBLISH',
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_VIEW',
      'ASSET_VIEW',
      'ATTENDANCE_VIEW',
      'AUDIT_LOG_VIEW',
      'CLASS_VIEW',
      'DASHBOARD_EXECUTIVE_VIEW',
      'DISCIPLINE_MANAGE',
      'DISCIPLINE_VIEW',
      'FEES_VIEW',
      'GRADE_APPROVE',
      'GRADE_PUBLISH',
      'GRADE_REVIEW',
      'GUARDIAN_VIEW',
      'HR_LEAVE_APPROVE',
      'HR_STAFF_VIEW',
      'INVENTORY_VIEW',
      'LIBRARY_VIEW',
      'MESSAGE_SEND',
      'PAYROLL_VIEW',
      'REPORT_CARD_GENERATE',
      'REPORT_CARD_VIEW',
      'STAFF_ATTENDANCE_VIEW',
      'STUDENT_VIEW',
      'SUBJECT_VIEW',
      'TENANT_SETTINGS_VIEW',
      'TIMETABLE_VIEW',
      'TRANSCRIPT_ISSUE',
    ],
  },
  {
    code: 'ACADEMIC_HEAD',
    name: 'Academic Head',
    description:
      'Owns the academic programme and the results pipeline up to approval.',
    scope: 'SCHOOL',
    permissions: [
      'ACADEMIC_YEAR_VIEW',
      'ANALYTICS_ACADEMIC_VIEW',
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_MANAGE',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_VIEW',
      'CLASS_MANAGE',
      'CLASS_VIEW',
      'GRADE_APPROVE',
      'GRADE_REVIEW',
      'GRADING_SCHEME_MANAGE',
      'MESSAGE_SEND',
      'REPORT_CARD_GENERATE',
      'REPORT_CARD_VIEW',
      'STUDENT_VIEW',
      'SUBJECT_MANAGE',
      'SUBJECT_VIEW',
      'TEACHING_ASSIGNMENT_MANAGE',
      'TIMETABLE_MANAGE',
      'TIMETABLE_SUBSTITUTE',
      'TIMETABLE_VIEW',
    ],
  },
  {
    code: 'REGISTRAR',
    name: 'Registrar',
    description:
      'Custodian of the student record and its documents.',
    scope: 'SCHOOL',
    permissions: [
      'ACADEMIC_YEAR_VIEW',
      'ADMISSION_APPLICATION_VIEW',
      'ADMISSION_ENROL',
      'CLASS_VIEW',
      'DATA_EXPORT',
      'DATA_IMPORT',
      'GUARDIAN_MANAGE',
      'GUARDIAN_VIEW',
      'REPORT_CARD_VIEW',
      'STUDENT_ARCHIVE',
      'STUDENT_CREATE',
      'STUDENT_DOCUMENT_MANAGE',
      'STUDENT_DOCUMENT_VIEW',
      'STUDENT_PROMOTE',
      'STUDENT_UPDATE',
      'STUDENT_VIEW',
      'TRANSCRIPT_ISSUE',
    ],
  },
  {
    code: 'ADMISSIONS_OFFICER',
    name: 'Admissions Officer',
    description:
      'Runs the admissions funnel. Cannot decide an offer alone.',
    scope: 'SCHOOL',
    permissions: [
      'ADMISSION_APPLICATION_MANAGE',
      'ADMISSION_APPLICATION_VIEW',
      'ADMISSION_ENROL',
      'ANNOUNCEMENT_VIEW',
      'CLASS_VIEW',
      'FEES_VIEW',
      'GUARDIAN_MANAGE',
      'GUARDIAN_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'TEACHER',
    name: 'Teacher',
    description:
      'Teaches assigned classes. Enters and submits marks, and deliberately cannot approve or publish the results they entered.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_MARK',
      'ATTENDANCE_VIEW',
      'CLASS_VIEW',
      'GRADE_EDIT_DRAFT',
      'GRADE_ENTER',
      'GRADE_SUBMIT',
      'HEALTH_ALERT_VIEW',
      'HR_LEAVE_REQUEST',
      'LIBRARY_VIEW',
      'MESSAGE_SEND',
      'PAYSLIP_VIEW_OWN',
      'REPORT_CARD_VIEW',
      'STUDENT_VIEW_OWN_CLASS',
      'STUDENT_READ',
      'GUARDIAN_READ',
      'ENROLMENT_READ',
      'SUBJECT_VIEW',
      'TIMETABLE_VIEW',
    ],
  },
  {
    code: 'CLASS_TEACHER',
    name: 'Class Teacher',
    description:
      'A teacher with pastoral responsibility for one class: adds remarks and sees that class in full.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_MARK',
      'ATTENDANCE_VIEW',
      'CLASS_VIEW',
      'DISCIPLINE_VIEW',
      'GRADE_EDIT_DRAFT',
      'GRADE_ENTER',
      'GRADE_SUBMIT',
      'GUARDIAN_VIEW',
      'HEALTH_ALERT_VIEW',
      'HR_LEAVE_REQUEST',
      'MESSAGE_SEND',
      'PAYSLIP_VIEW_OWN',
      'REPORT_CARD_GENERATE',
      'REPORT_CARD_VIEW',
      'STUDENT_VIEW_OWN_CLASS',
      'SUBJECT_VIEW',
      'TIMETABLE_VIEW',
    ],
  },
  {
    code: 'HEAD_OF_DEPARTMENT',
    name: 'Head of Department',
    description:
      'Reviews marks submitted by the department before they reach the academic head.',
    scope: 'SCHOOL',
    permissions: [
      'ANALYTICS_ACADEMIC_VIEW',
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_MANAGE',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_VIEW',
      'CLASS_VIEW',
      'GRADE_EDIT_DRAFT',
      'GRADE_ENTER',
      'GRADE_REVIEW',
      'GRADE_SUBMIT',
      'HR_LEAVE_APPROVE',
      'HR_LEAVE_REQUEST',
      'MESSAGE_SEND',
      'PAYSLIP_VIEW_OWN',
      'REPORT_CARD_VIEW',
      'STUDENT_VIEW_OWN_CLASS',
      'SUBJECT_MANAGE',
      'SUBJECT_VIEW',
      'TEACHING_ASSIGNMENT_MANAGE',
      'TIMETABLE_VIEW',
    ],
  },
  {
    code: 'BURSAR',
    name: 'Bursar',
    description:
      'Owns fee collection and cash. Records payments and issues receipts; refund approval and journal posting sit with a different holder (maker-checker, spec 134).',
    scope: 'SCHOOL',
    permissions: [
      'ACCOUNTING_REPORT_VIEW',
      'ACCOUNTING_VIEW',
      'ANALYTICS_FINANCE_VIEW',
      'DATA_EXPORT',
      'FEES_DISCOUNT',
      'FEES_STRUCTURE_MANAGE',
      'FEES_VIEW',
      'GUARDIAN_VIEW',
      'INVOICE_CANCEL',
      'INVOICE_CREATE',
      'MESSAGE_SEND',
      'PAYMENT_ALLOCATE',
      'PAYMENT_RECORD',
      'PAYMENT_REFUND',
      'RECEIPT_ISSUE',
      'RECONCILIATION_RESOLVE',
      'RECONCILIATION_VIEW',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'ACCOUNTANT',
    name: 'Accountant',
    description:
      'Prepares journals and reports. Cannot approve or post their own journal.',
    scope: 'SCHOOL',
    permissions: [
      'ACCOUNTING_COA_MANAGE',
      'ACCOUNTING_JOURNAL_CREATE',
      'ACCOUNTING_REPORT_VIEW',
      'ACCOUNTING_VIEW',
      'ANALYTICS_FINANCE_VIEW',
      'ASSET_VIEW',
      'BUDGET_MANAGE',
      'DATA_EXPORT',
      'FEES_VIEW',
      'INVENTORY_VIEW',
      'RECONCILIATION_RESOLVE',
      'RECONCILIATION_VIEW',
      'TAX_RULE_MANAGE',
    ],
  },
  {
    code: 'FINANCE_MANAGER',
    name: 'Finance Manager',
    description:
      'The checker in maker-checker: approves and posts journals, approves refunds, closes periods.',
    scope: 'SCHOOL',
    permissions: [
      'ACCOUNTING_COA_MANAGE',
      'ACCOUNTING_JOURNAL_APPROVE',
      'ACCOUNTING_JOURNAL_CREATE',
      'ACCOUNTING_JOURNAL_POST',
      'ACCOUNTING_JOURNAL_REVERSE',
      'ACCOUNTING_PERIOD_CLOSE',
      'ACCOUNTING_REPORT_VIEW',
      'ACCOUNTING_VIEW',
      'ANALYTICS_FINANCE_VIEW',
      'AUDIT_LOG_VIEW',
      'BUDGET_MANAGE',
      'DATA_EXPORT',
      'FEES_VIEW',
      'FEES_WAIVE',
      'PAYMENT_REFUND_APPROVE',
      'PAYROLL_VIEW',
      'RECONCILIATION_RESOLVE',
      'RECONCILIATION_VIEW',
      'TAX_RULE_MANAGE',
    ],
  },
  {
    code: 'HR_MANAGER',
    name: 'HR Manager',
    description:
      'Owns the staff lifecycle. Sees salary data; does not approve payroll.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'DATA_EXPORT',
      'HR_CONTRACT_MANAGE',
      'HR_DISCIPLINARY_MANAGE',
      'HR_LEAVE_APPROVE',
      'HR_PERFORMANCE_MANAGE',
      'HR_SALARY_MANAGE',
      'HR_SALARY_VIEW',
      'HR_STAFF_MANAGE',
      'HR_STAFF_VIEW',
      'MESSAGE_SEND',
      'PAYROLL_VIEW',
      'STAFF_ATTENDANCE_VIEW',
      'USER_INVITE',
      'USER_VIEW',
    ],
  },
  {
    code: 'PAYROLL_OFFICER',
    name: 'Payroll Officer',
    description:
      'Prepares payroll. Approval and posting are deliberately absent (spec 158).',
    scope: 'SCHOOL',
    permissions: [
      'HR_SALARY_VIEW',
      'HR_STAFF_VIEW',
      'PAYROLL_PREPARE',
      'PAYROLL_STATUTORY_MANAGE',
      'PAYROLL_VIEW',
      'PAYSLIP_VIEW_ALL',
      'STAFF_ATTENDANCE_VIEW',
    ],
  },
  {
    code: 'LIBRARIAN',
    name: 'Librarian',
    description:
      'Runs the library catalogue and circulation.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'LIBRARY_CIRCULATE',
      'LIBRARY_MANAGE',
      'LIBRARY_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'NURSE',
    name: 'Nurse / Health Officer',
    description:
      'The only ordinary school role holding health records. Access is audited.',
    scope: 'SCHOOL',
    permissions: [
      'GUARDIAN_VIEW',
      'HEALTH_ALERT_VIEW',
      'HEALTH_RECORD_MANAGE',
      'HEALTH_RECORD_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'COUNSELLOR',
    name: 'Counsellor',
    description:
      'Confidential case work. Counselling notes are not visible to teachers or administrators.',
    scope: 'SCHOOL',
    permissions: [
      'COUNSELLING_MANAGE',
      'COUNSELLING_VIEW',
      'DISCIPLINE_VIEW',
      'GUARDIAN_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'TRANSPORT_MANAGER',
    name: 'Transport Manager',
    description:
      'Routes and vehicles. Pupil address data is restricted to what routing requires.',
    scope: 'SCHOOL',
    permissions: [
      'ASSET_VIEW',
      'GUARDIAN_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
      'TRANSPORT_MANAGE',
      'TRANSPORT_VIEW',
    ],
  },
  {
    code: 'HOSTEL_MANAGER',
    name: 'Hostel Manager',
    description:
      'Boarding allocation and pastoral care in the hostel.',
    scope: 'SCHOOL',
    permissions: [
      'DISCIPLINE_VIEW',
      'GUARDIAN_VIEW',
      'HEALTH_ALERT_VIEW',
      'HOSTEL_MANAGE',
      'HOSTEL_VIEW',
      'MESSAGE_SEND',
      'STUDENT_VIEW',
    ],
  },
  {
    code: 'STOREKEEPER',
    name: 'Storekeeper',
    description:
      'Stock movements. Adjustments require the separate adjust permission.',
    scope: 'SCHOOL',
    permissions: [
      'ASSET_VIEW',
      'INVENTORY_MANAGE',
      'INVENTORY_VIEW',
      'PROCUREMENT_RECEIVE',
    ],
  },
  {
    code: 'PROCUREMENT_OFFICER',
    name: 'Procurement Officer',
    description:
      'Raises requisitions and orders. Approval sits with a different holder.',
    scope: 'SCHOOL',
    permissions: [
      'ACCOUNTING_VIEW',
      'ASSET_VIEW',
      'INVENTORY_VIEW',
      'PROCUREMENT_ORDER',
      'PROCUREMENT_RECEIVE',
      'PROCUREMENT_REQUEST',
    ],
  },
  {
    code: 'ICT_ADMINISTRATOR',
    name: 'ICT Administrator',
    description:
      'Technical administration. Deliberately excludes finance, payroll and health records: administering the system is not a reason to read a child’s medical notes.',
    scope: 'SCHOOL',
    permissions: [
      'AUDIT_LOG_VIEW',
      'DATA_IMPORT',
      'NOTIFICATION_FAILURE_VIEW',
      'NOTIFICATION_SETTINGS_MANAGE',
      'ROLE_VIEW',
      'SESSION_REVOKE',
      'TENANT_API_KEY_MANAGE',
      'TENANT_INTEGRATION_MANAGE',
      'TENANT_SETTINGS_VIEW',
      'USER_INVITE',
      'USER_VIEW',
    ],
  },
  {
    code: 'STUDENT',
    name: 'Student',
    description:
      'Sees their own record only. Row-level filtering to the student is applied on top of these permissions.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_VIEW',
      'LIBRARY_VIEW',
      'MESSAGE_SEND',
      'REPORT_CARD_VIEW',
      'TIMETABLE_VIEW',
    ],
  },
  {
    code: 'GUARDIAN',
    name: 'Parent / Guardian',
    description:
      'Sees linked wards only. Row-level filtering to the guardian link is applied on top of these permissions.',
    scope: 'SCHOOL',
    permissions: [
      'ANNOUNCEMENT_VIEW',
      'ASSESSMENT_VIEW',
      'ATTENDANCE_VIEW',
      'FEES_VIEW',
      'HEALTH_ALERT_VIEW',
      'LIBRARY_VIEW',
      'MESSAGE_SEND',
      'REPORT_CARD_VIEW',
      'TIMETABLE_VIEW',
    ],
  },
];

/** Every permission code, for tests that assert code and catalogue agree. */
export const PERMISSION_CODES = PERMISSIONS.map((p) => p.code);
