-- ==================================================================================
-- V0003 - Permission catalogue and system role templates
--
-- GENERATED by scripts/generate-rbac-seed.mjs from
-- io.sankofa.school.identity.authz.Permissions. Do not hand-edit: regenerate.
--
-- PermissionCatalogueIT asserts the Java constants and these rows agree in BOTH
-- directions, so a permission cannot be referenced in code without existing here,
-- and a row cannot linger here with nothing referencing it.
--
-- Least privilege is the design rule below. A permission being ABSENT from a role is
-- a decision, not an oversight: a teacher does not receive payroll, accounting,
-- health, discipline or counselling access by virtue of being a teacher, and the
-- officer who prepares payroll cannot approve it (spec 134, 158).
-- ==================================================================================

-- 142 permissions; 30 sensitive, 11 child-sensitive.
INSERT INTO identity.permission (id, code, module, description, is_sensitive, is_child_sensitive) VALUES
    (gen_random_uuid(), 'PLATFORM_TENANT_VIEW', 'platform', 'Platform tenant view', false, false),
    (gen_random_uuid(), 'PLATFORM_TENANT_PROVISION', 'platform', 'Platform tenant provision', false, false),
    (gen_random_uuid(), 'PLATFORM_TENANT_SUSPEND', 'platform', 'Platform tenant suspend', true, false),
    (gen_random_uuid(), 'PLATFORM_SUBSCRIPTION_MANAGE', 'platform', 'Platform subscription manage', false, false),
    (gen_random_uuid(), 'PLATFORM_HEALTH_VIEW', 'platform', 'Platform health view', false, false),
    (gen_random_uuid(), 'PLATFORM_SUPPORT_REQUEST_ACCESS', 'platform', 'Request time-boxed support access to a tenant', false, false),
    (gen_random_uuid(), 'PLATFORM_SUPPORT_APPROVE_ACCESS', 'platform', 'Approve a support access request', true, false),
    (gen_random_uuid(), 'PLATFORM_AUDIT_VIEW', 'platform', 'Platform audit view', false, false),
    (gen_random_uuid(), 'TENANT_SETTINGS_VIEW', 'tenant_settings', 'Tenant settings view', false, false),
    (gen_random_uuid(), 'TENANT_SETTINGS_MANAGE', 'tenant_settings', 'Tenant settings manage', false, false),
    (gen_random_uuid(), 'TENANT_BRANDING_MANAGE', 'tenant_settings', 'Tenant branding manage', false, false),
    (gen_random_uuid(), 'TENANT_CAMPUS_MANAGE', 'tenant_settings', 'Tenant campus manage', false, false),
    (gen_random_uuid(), 'TENANT_INTEGRATION_MANAGE', 'tenant_settings', 'Tenant integration manage', false, false),
    (gen_random_uuid(), 'TENANT_API_KEY_MANAGE', 'tenant_settings', 'Tenant api key manage', true, false),
    (gen_random_uuid(), 'TENANT_RETENTION_MANAGE', 'tenant_settings', 'Tenant retention manage', true, false),
    (gen_random_uuid(), 'USER_VIEW', 'identity_and_access', 'User view', false, false),
    (gen_random_uuid(), 'USER_INVITE', 'identity_and_access', 'User invite', false, false),
    (gen_random_uuid(), 'USER_SUSPEND', 'identity_and_access', 'User suspend', false, false),
    (gen_random_uuid(), 'ROLE_VIEW', 'identity_and_access', 'Role view', false, false),
    (gen_random_uuid(), 'ROLE_MANAGE', 'identity_and_access', 'Role manage', true, false),
    (gen_random_uuid(), 'PERMISSION_ASSIGN', 'identity_and_access', 'Permission assign', true, false),
    (gen_random_uuid(), 'SESSION_REVOKE', 'identity_and_access', 'Session revoke', true, false),
    (gen_random_uuid(), 'ACADEMIC_YEAR_VIEW', 'academic_structure', 'Academic year view', false, false),
    (gen_random_uuid(), 'ACADEMIC_YEAR_MANAGE', 'academic_structure', 'Academic year manage', false, false),
    (gen_random_uuid(), 'CLASS_VIEW', 'academic_structure', 'Class view', false, false),
    (gen_random_uuid(), 'CLASS_MANAGE', 'academic_structure', 'Class manage', false, false),
    (gen_random_uuid(), 'SUBJECT_VIEW', 'academic_structure', 'Subject view', false, false),
    (gen_random_uuid(), 'SUBJECT_MANAGE', 'academic_structure', 'Subject manage', false, false),
    (gen_random_uuid(), 'TEACHING_ASSIGNMENT_MANAGE', 'academic_structure', 'Teaching assignment manage', false, false),
    (gen_random_uuid(), 'TIMETABLE_VIEW', 'academic_structure', 'Timetable view', false, false),
    (gen_random_uuid(), 'TIMETABLE_MANAGE', 'academic_structure', 'Timetable manage', false, false),
    (gen_random_uuid(), 'TIMETABLE_SUBSTITUTE', 'academic_structure', 'Timetable substitute', false, false),
    (gen_random_uuid(), 'STUDENT_VIEW', 'students', 'Student view', false, false),
    (gen_random_uuid(), 'STUDENT_VIEW_OWN_CLASS', 'students', 'View students in classes the holder teaches, and no others', false, false),
    (gen_random_uuid(), 'STUDENT_CREATE', 'students', 'Student create', false, false),
    (gen_random_uuid(), 'STUDENT_UPDATE', 'students', 'Student update', false, false),
    (gen_random_uuid(), 'STUDENT_ARCHIVE', 'students', 'Student archive', false, false),
    (gen_random_uuid(), 'STUDENT_PROMOTE', 'students', 'Student promote', false, false),
    (gen_random_uuid(), 'STUDENT_DOCUMENT_VIEW', 'students', 'Student document view', false, true),
    (gen_random_uuid(), 'STUDENT_DOCUMENT_MANAGE', 'students', 'Student document manage', false, true),
    (gen_random_uuid(), 'GUARDIAN_VIEW', 'students', 'Guardian view', false, false),
    (gen_random_uuid(), 'GUARDIAN_MANAGE', 'students', 'Guardian manage', false, false),
    (gen_random_uuid(), 'ADMISSION_APPLICATION_VIEW', 'admissions', 'Admission application view', false, false),
    (gen_random_uuid(), 'ADMISSION_APPLICATION_MANAGE', 'admissions', 'Admission application manage', false, false),
    (gen_random_uuid(), 'ADMISSION_DECIDE', 'admissions', 'Admission decide', false, false),
    (gen_random_uuid(), 'ADMISSION_ENROL', 'admissions', 'Admission enrol', false, false),
    (gen_random_uuid(), 'ATTENDANCE_VIEW', 'attendance', 'Attendance view', false, false),
    (gen_random_uuid(), 'ATTENDANCE_MARK', 'attendance', 'Attendance mark', false, false),
    (gen_random_uuid(), 'ATTENDANCE_CORRECT', 'attendance', 'Attendance correct', false, false),
    (gen_random_uuid(), 'ATTENDANCE_LOCK', 'attendance', 'Attendance lock', false, false),
    (gen_random_uuid(), 'STAFF_ATTENDANCE_VIEW', 'attendance', 'Staff attendance view', false, false),
    (gen_random_uuid(), 'ASSESSMENT_VIEW', 'assessment_and_grading', 'Assessment view', false, false),
    (gen_random_uuid(), 'ASSESSMENT_MANAGE', 'assessment_and_grading', 'Assessment manage', false, false),
    (gen_random_uuid(), 'GRADE_ENTER', 'assessment_and_grading', 'Grade enter', false, false),
    (gen_random_uuid(), 'GRADE_EDIT_DRAFT', 'assessment_and_grading', 'Grade edit draft', false, false),
    (gen_random_uuid(), 'GRADE_SUBMIT', 'assessment_and_grading', 'Grade submit', false, false),
    (gen_random_uuid(), 'GRADE_REVIEW', 'assessment_and_grading', 'Grade review', false, false),
    (gen_random_uuid(), 'GRADE_APPROVE', 'assessment_and_grading', 'Grade approve', false, false),
    (gen_random_uuid(), 'GRADE_PUBLISH', 'assessment_and_grading', 'Grade publish', true, false),
    (gen_random_uuid(), 'GRADE_AMEND_PUBLISHED', 'assessment_and_grading', 'Amend a published mark, creating an auditable amendment record', true, false),
    (gen_random_uuid(), 'GRADING_SCHEME_MANAGE', 'assessment_and_grading', 'Grading scheme manage', false, false),
    (gen_random_uuid(), 'REPORT_CARD_VIEW', 'assessment_and_grading', 'Report card view', false, false),
    (gen_random_uuid(), 'REPORT_CARD_GENERATE', 'assessment_and_grading', 'Report card generate', false, false),
    (gen_random_uuid(), 'TRANSCRIPT_ISSUE', 'assessment_and_grading', 'Transcript issue', false, false),
    (gen_random_uuid(), 'FEES_VIEW', 'fees_and_payments', 'Fees view', false, false),
    (gen_random_uuid(), 'FEES_STRUCTURE_MANAGE', 'fees_and_payments', 'Fees structure manage', false, false),
    (gen_random_uuid(), 'INVOICE_CREATE', 'fees_and_payments', 'Invoice create', false, false),
    (gen_random_uuid(), 'INVOICE_CANCEL', 'fees_and_payments', 'Invoice cancel', false, false),
    (gen_random_uuid(), 'FEES_DISCOUNT', 'fees_and_payments', 'Fees discount', true, false),
    (gen_random_uuid(), 'FEES_WAIVE', 'fees_and_payments', 'Fees waive', true, false),
    (gen_random_uuid(), 'PAYMENT_RECORD', 'fees_and_payments', 'Payment record', false, false),
    (gen_random_uuid(), 'PAYMENT_ALLOCATE', 'fees_and_payments', 'Payment allocate', false, false),
    (gen_random_uuid(), 'PAYMENT_REFUND', 'fees_and_payments', 'Payment refund', true, false),
    (gen_random_uuid(), 'PAYMENT_REFUND_APPROVE', 'fees_and_payments', 'Payment refund approve', true, false),
    (gen_random_uuid(), 'RECEIPT_ISSUE', 'fees_and_payments', 'Receipt issue', false, false),
    (gen_random_uuid(), 'RECONCILIATION_VIEW', 'fees_and_payments', 'Reconciliation view', false, false),
    (gen_random_uuid(), 'RECONCILIATION_RESOLVE', 'fees_and_payments', 'Reconciliation resolve', false, false),
    (gen_random_uuid(), 'ACCOUNTING_VIEW', 'accounting', 'Accounting view', false, false),
    (gen_random_uuid(), 'ACCOUNTING_COA_MANAGE', 'accounting', 'Accounting coa manage', false, false),
    (gen_random_uuid(), 'ACCOUNTING_JOURNAL_CREATE', 'accounting', 'Accounting journal create', false, false),
    (gen_random_uuid(), 'ACCOUNTING_JOURNAL_APPROVE', 'accounting', 'Accounting journal approve', true, false),
    (gen_random_uuid(), 'ACCOUNTING_JOURNAL_POST', 'accounting', 'Accounting journal post', true, false),
    (gen_random_uuid(), 'ACCOUNTING_JOURNAL_REVERSE', 'accounting', 'Accounting journal reverse', true, false),
    (gen_random_uuid(), 'ACCOUNTING_PERIOD_CLOSE', 'accounting', 'Accounting period close', true, false),
    (gen_random_uuid(), 'ACCOUNTING_PERIOD_REOPEN', 'accounting', 'Reopen a closed accounting period, with a recorded reason', true, false),
    (gen_random_uuid(), 'ACCOUNTING_REPORT_VIEW', 'accounting', 'Accounting report view', false, false),
    (gen_random_uuid(), 'TAX_RULE_MANAGE', 'accounting', 'Tax rule manage', false, false),
    (gen_random_uuid(), 'BUDGET_MANAGE', 'accounting', 'Budget manage', false, false),
    (gen_random_uuid(), 'HR_STAFF_VIEW', 'hr', 'Hr staff view', false, false),
    (gen_random_uuid(), 'HR_STAFF_MANAGE', 'hr', 'Hr staff manage', false, false),
    (gen_random_uuid(), 'HR_CONTRACT_MANAGE', 'hr', 'Hr contract manage', false, false),
    (gen_random_uuid(), 'HR_SALARY_VIEW', 'hr', 'Hr salary view', true, false),
    (gen_random_uuid(), 'HR_SALARY_MANAGE', 'hr', 'Hr salary manage', true, false),
    (gen_random_uuid(), 'HR_LEAVE_REQUEST', 'hr', 'Hr leave request', false, false),
    (gen_random_uuid(), 'HR_LEAVE_APPROVE', 'hr', 'Hr leave approve', false, false),
    (gen_random_uuid(), 'HR_PERFORMANCE_MANAGE', 'hr', 'Hr performance manage', false, false),
    (gen_random_uuid(), 'HR_DISCIPLINARY_MANAGE', 'hr', 'Hr disciplinary manage', false, false),
    (gen_random_uuid(), 'PAYROLL_VIEW', 'payroll', 'Payroll view', false, false),
    (gen_random_uuid(), 'PAYROLL_PREPARE', 'payroll', 'Payroll prepare', false, false),
    (gen_random_uuid(), 'PAYROLL_APPROVE', 'payroll', 'Payroll approve', true, false),
    (gen_random_uuid(), 'PAYROLL_POST', 'payroll', 'Payroll post', true, false),
    (gen_random_uuid(), 'PAYROLL_STATUTORY_MANAGE', 'payroll', 'Payroll statutory manage', true, false),
    (gen_random_uuid(), 'PAYSLIP_VIEW_OWN', 'payroll', 'View only the holder’s own payslips', false, false),
    (gen_random_uuid(), 'PAYSLIP_VIEW_ALL', 'payroll', 'View any employee’s payslip', true, false),
    (gen_random_uuid(), 'LIBRARY_VIEW', 'library_inventory_procurement_assets', 'Library view', false, false),
    (gen_random_uuid(), 'LIBRARY_MANAGE', 'library_inventory_procurement_assets', 'Library manage', false, false),
    (gen_random_uuid(), 'LIBRARY_CIRCULATE', 'library_inventory_procurement_assets', 'Library circulate', false, false),
    (gen_random_uuid(), 'INVENTORY_VIEW', 'library_inventory_procurement_assets', 'Inventory view', false, false),
    (gen_random_uuid(), 'INVENTORY_MANAGE', 'library_inventory_procurement_assets', 'Inventory manage', false, false),
    (gen_random_uuid(), 'INVENTORY_ADJUST', 'library_inventory_procurement_assets', 'Inventory adjust', true, false),
    (gen_random_uuid(), 'PROCUREMENT_REQUEST', 'library_inventory_procurement_assets', 'Procurement request', false, false),
    (gen_random_uuid(), 'PROCUREMENT_APPROVE', 'library_inventory_procurement_assets', 'Procurement approve', false, false),
    (gen_random_uuid(), 'PROCUREMENT_ORDER', 'library_inventory_procurement_assets', 'Procurement order', false, false),
    (gen_random_uuid(), 'PROCUREMENT_RECEIVE', 'library_inventory_procurement_assets', 'Procurement receive', false, false),
    (gen_random_uuid(), 'ASSET_VIEW', 'library_inventory_procurement_assets', 'Asset view', false, false),
    (gen_random_uuid(), 'ASSET_MANAGE', 'library_inventory_procurement_assets', 'Asset manage', false, false),
    (gen_random_uuid(), 'ASSET_DISPOSE', 'library_inventory_procurement_assets', 'Asset dispose', true, false),
    (gen_random_uuid(), 'TRANSPORT_VIEW', 'operations', 'Transport view', false, true),
    (gen_random_uuid(), 'TRANSPORT_MANAGE', 'operations', 'Transport manage', false, true),
    (gen_random_uuid(), 'HOSTEL_VIEW', 'operations', 'Hostel view', false, false),
    (gen_random_uuid(), 'HOSTEL_MANAGE', 'operations', 'Hostel manage', false, false),
    (gen_random_uuid(), 'HEALTH_RECORD_VIEW', 'restricted_personal_records', 'Health record view', false, true),
    (gen_random_uuid(), 'HEALTH_RECORD_MANAGE', 'restricted_personal_records', 'Health record manage', false, true),
    (gen_random_uuid(), 'HEALTH_ALERT_VIEW', 'restricted_personal_records', 'Health alert view', false, true),
    (gen_random_uuid(), 'DISCIPLINE_VIEW', 'restricted_personal_records', 'Discipline view', false, true),
    (gen_random_uuid(), 'DISCIPLINE_MANAGE', 'restricted_personal_records', 'Discipline manage', false, true),
    (gen_random_uuid(), 'COUNSELLING_VIEW', 'restricted_personal_records', 'Counselling view', false, true),
    (gen_random_uuid(), 'COUNSELLING_MANAGE', 'restricted_personal_records', 'Counselling manage', false, true),
    (gen_random_uuid(), 'ANNOUNCEMENT_VIEW', 'communications', 'Announcement view', false, false),
    (gen_random_uuid(), 'ANNOUNCEMENT_PUBLISH', 'communications', 'Announcement publish', false, false),
    (gen_random_uuid(), 'NOTIFICATION_TEMPLATE_MANAGE', 'communications', 'Notification template manage', false, false),
    (gen_random_uuid(), 'NOTIFICATION_SETTINGS_MANAGE', 'communications', 'Notification settings manage', false, false),
    (gen_random_uuid(), 'NOTIFICATION_FAILURE_VIEW', 'communications', 'Notification failure view', false, false),
    (gen_random_uuid(), 'SMS_SEND_BULK', 'communications', 'Send SMS to a large recipient list, subject to confirmation and quota', true, false),
    (gen_random_uuid(), 'MESSAGE_SEND', 'communications', 'Message send', false, false),
    (gen_random_uuid(), 'DASHBOARD_EXECUTIVE_VIEW', 'analytics_audit_data', 'Dashboard executive view', false, false),
    (gen_random_uuid(), 'ANALYTICS_FINANCE_VIEW', 'analytics_audit_data', 'Analytics finance view', false, false),
    (gen_random_uuid(), 'ANALYTICS_ACADEMIC_VIEW', 'analytics_audit_data', 'Analytics academic view', false, false),
    (gen_random_uuid(), 'AUDIT_LOG_VIEW', 'analytics_audit_data', 'Audit log view', true, false),
    (gen_random_uuid(), 'DATA_EXPORT', 'analytics_audit_data', 'Data export', true, false),
    (gen_random_uuid(), 'DATA_IMPORT', 'analytics_audit_data', 'Data import', false, false),
    (gen_random_uuid(), 'PRIVACY_REQUEST_HANDLE', 'analytics_audit_data', 'Privacy request handle', true, false)
ON CONFLICT (code) DO NOTHING;

-- 26 system role templates. tenant_id IS NULL marks a template that every
-- tenant may use. A school can copy one into its own editable role; it cannot alter
-- the template itself.
INSERT INTO identity.role (id, tenant_id, code, name, description, scope, is_system, is_assignable) VALUES
    (gen_random_uuid(), NULL, 'PLATFORM_SUPER_ADMIN', 'Platform Super Admin', 'Operates the platform itself. Deliberately holds no permission over a school’s student, health, discipline or academic records; entering a tenant requires a time-boxed, reasoned support grant.', 'PLATFORM', true, true),
    (gen_random_uuid(), NULL, 'PLATFORM_SUPPORT', 'Platform Support', 'Reads platform health and may request, never self-approve, tenant access.', 'PLATFORM', true, true),
    (gen_random_uuid(), NULL, 'SCHOOL_OWNER', 'School Owner', 'Full authority within one school, including subscription and role administration.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'SCHOOL_ADMIN', 'School Administrator', 'Day-to-day administration of people, structure and settings. Not finance approval, not payroll approval.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'HEADMASTER', 'Headmaster / Principal', 'Executive oversight. Reads widely and approves results; does not post journals or run payroll.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'ACADEMIC_HEAD', 'Academic Head', 'Owns the academic programme and the results pipeline up to approval.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'REGISTRAR', 'Registrar', 'Custodian of the student record and its documents.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'ADMISSIONS_OFFICER', 'Admissions Officer', 'Runs the admissions funnel. Cannot decide an offer alone.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'TEACHER', 'Teacher', 'Teaches assigned classes. Enters and submits marks, and deliberately cannot approve or publish the results they entered.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'CLASS_TEACHER', 'Class Teacher', 'A teacher with pastoral responsibility for one class: adds remarks and sees that class in full.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'HEAD_OF_DEPARTMENT', 'Head of Department', 'Reviews marks submitted by the department before they reach the academic head.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'BURSAR', 'Bursar', 'Owns fee collection and cash. Records payments and issues receipts; refund approval and journal posting sit with a different holder (maker-checker, spec 134).', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'ACCOUNTANT', 'Accountant', 'Prepares journals and reports. Cannot approve or post their own journal.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'FINANCE_MANAGER', 'Finance Manager', 'The checker in maker-checker: approves and posts journals, approves refunds, closes periods.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'HR_MANAGER', 'HR Manager', 'Owns the staff lifecycle. Sees salary data; does not approve payroll.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'PAYROLL_OFFICER', 'Payroll Officer', 'Prepares payroll. Approval and posting are deliberately absent (spec 158).', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'LIBRARIAN', 'Librarian', 'Runs the library catalogue and circulation.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'NURSE', 'Nurse / Health Officer', 'The only ordinary school role holding health records. Access is audited.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'COUNSELLOR', 'Counsellor', 'Confidential case work. Counselling notes are not visible to teachers or administrators.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'TRANSPORT_MANAGER', 'Transport Manager', 'Routes and vehicles. Pupil address data is restricted to what routing requires.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'HOSTEL_MANAGER', 'Hostel Manager', 'Boarding allocation and pastoral care in the hostel.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'STOREKEEPER', 'Storekeeper', 'Stock movements. Adjustments require the separate adjust permission.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'PROCUREMENT_OFFICER', 'Procurement Officer', 'Raises requisitions and orders. Approval sits with a different holder.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'ICT_ADMINISTRATOR', 'ICT Administrator', 'Technical administration. Deliberately excludes finance, payroll and health records: administering the system is not a reason to read a child’s medical notes.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'STUDENT', 'Student', 'Sees their own record only. Row-level filtering to the student is applied on top of these permissions.', 'SCHOOL', true, true),
    (gen_random_uuid(), NULL, 'GUARDIAN', 'Parent / Guardian', 'Sees linked wards only. Row-level filtering to the guardian link is applied on top of these permissions.', 'SCHOOL', true, true)
ON CONFLICT DO NOTHING;

-- Platform Super Admin: 7 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'PLATFORM_AUDIT_VIEW',
        'PLATFORM_HEALTH_VIEW',
        'PLATFORM_SUBSCRIPTION_MANAGE',
        'PLATFORM_SUPPORT_APPROVE_ACCESS',
        'PLATFORM_TENANT_PROVISION',
        'PLATFORM_TENANT_SUSPEND',
        'PLATFORM_TENANT_VIEW'
       )
 WHERE r.code = 'PLATFORM_SUPER_ADMIN' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Platform Support: 3 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'PLATFORM_HEALTH_VIEW',
        'PLATFORM_SUPPORT_REQUEST_ACCESS',
        'PLATFORM_TENANT_VIEW'
       )
 WHERE r.code = 'PLATFORM_SUPPORT' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- School Owner: 26 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACCOUNTING_REPORT_VIEW',
        'ACCOUNTING_VIEW',
        'ANALYTICS_ACADEMIC_VIEW',
        'ANALYTICS_FINANCE_VIEW',
        'AUDIT_LOG_VIEW',
        'DASHBOARD_EXECUTIVE_VIEW',
        'DATA_EXPORT',
        'FEES_VIEW',
        'HR_STAFF_VIEW',
        'PAYROLL_VIEW',
        'PERMISSION_ASSIGN',
        'PRIVACY_REQUEST_HANDLE',
        'ROLE_MANAGE',
        'ROLE_VIEW',
        'SESSION_REVOKE',
        'STUDENT_VIEW',
        'TENANT_API_KEY_MANAGE',
        'TENANT_BRANDING_MANAGE',
        'TENANT_CAMPUS_MANAGE',
        'TENANT_INTEGRATION_MANAGE',
        'TENANT_RETENTION_MANAGE',
        'TENANT_SETTINGS_MANAGE',
        'TENANT_SETTINGS_VIEW',
        'USER_INVITE',
        'USER_SUSPEND',
        'USER_VIEW'
       )
 WHERE r.code = 'SCHOOL_OWNER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- School Administrator: 44 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACADEMIC_YEAR_MANAGE',
        'ACADEMIC_YEAR_VIEW',
        'ADMISSION_APPLICATION_MANAGE',
        'ADMISSION_APPLICATION_VIEW',
        'ADMISSION_ENROL',
        'ANNOUNCEMENT_PUBLISH',
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_MANAGE',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_CORRECT',
        'ATTENDANCE_LOCK',
        'ATTENDANCE_VIEW',
        'AUDIT_LOG_VIEW',
        'CLASS_MANAGE',
        'CLASS_VIEW',
        'DATA_EXPORT',
        'DATA_IMPORT',
        'GUARDIAN_MANAGE',
        'GUARDIAN_VIEW',
        'MESSAGE_SEND',
        'NOTIFICATION_FAILURE_VIEW',
        'NOTIFICATION_SETTINGS_MANAGE',
        'NOTIFICATION_TEMPLATE_MANAGE',
        'REPORT_CARD_GENERATE',
        'REPORT_CARD_VIEW',
        'ROLE_VIEW',
        'STUDENT_ARCHIVE',
        'STUDENT_CREATE',
        'STUDENT_PROMOTE',
        'STUDENT_UPDATE',
        'STUDENT_VIEW',
        'SUBJECT_MANAGE',
        'SUBJECT_VIEW',
        'TEACHING_ASSIGNMENT_MANAGE',
        'TENANT_BRANDING_MANAGE',
        'TENANT_CAMPUS_MANAGE',
        'TENANT_SETTINGS_MANAGE',
        'TENANT_SETTINGS_VIEW',
        'TIMETABLE_MANAGE',
        'TIMETABLE_SUBSTITUTE',
        'TIMETABLE_VIEW',
        'USER_INVITE',
        'USER_SUSPEND',
        'USER_VIEW'
       )
 WHERE r.code = 'SCHOOL_ADMIN' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Headmaster / Principal: 36 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACADEMIC_YEAR_VIEW',
        'ACCOUNTING_REPORT_VIEW',
        'ACCOUNTING_VIEW',
        'ADMISSION_APPLICATION_VIEW',
        'ADMISSION_DECIDE',
        'ANALYTICS_ACADEMIC_VIEW',
        'ANALYTICS_FINANCE_VIEW',
        'ANNOUNCEMENT_PUBLISH',
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_VIEW',
        'ASSET_VIEW',
        'ATTENDANCE_VIEW',
        'AUDIT_LOG_VIEW',
        'CLASS_VIEW',
        'DASHBOARD_EXECUTIVE_VIEW',
        'DISCIPLINE_MANAGE',
        'DISCIPLINE_VIEW',
        'FEES_VIEW',
        'GRADE_APPROVE',
        'GRADE_PUBLISH',
        'GRADE_REVIEW',
        'GUARDIAN_VIEW',
        'HR_LEAVE_APPROVE',
        'HR_STAFF_VIEW',
        'INVENTORY_VIEW',
        'LIBRARY_VIEW',
        'MESSAGE_SEND',
        'PAYROLL_VIEW',
        'REPORT_CARD_GENERATE',
        'REPORT_CARD_VIEW',
        'STAFF_ATTENDANCE_VIEW',
        'STUDENT_VIEW',
        'SUBJECT_VIEW',
        'TENANT_SETTINGS_VIEW',
        'TIMETABLE_VIEW',
        'TRANSCRIPT_ISSUE'
       )
 WHERE r.code = 'HEADMASTER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Academic Head: 21 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACADEMIC_YEAR_VIEW',
        'ANALYTICS_ACADEMIC_VIEW',
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_MANAGE',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_VIEW',
        'CLASS_MANAGE',
        'CLASS_VIEW',
        'GRADE_APPROVE',
        'GRADE_REVIEW',
        'GRADING_SCHEME_MANAGE',
        'MESSAGE_SEND',
        'REPORT_CARD_GENERATE',
        'REPORT_CARD_VIEW',
        'STUDENT_VIEW',
        'SUBJECT_MANAGE',
        'SUBJECT_VIEW',
        'TEACHING_ASSIGNMENT_MANAGE',
        'TIMETABLE_MANAGE',
        'TIMETABLE_SUBSTITUTE',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'ACADEMIC_HEAD' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Registrar: 17 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACADEMIC_YEAR_VIEW',
        'ADMISSION_APPLICATION_VIEW',
        'ADMISSION_ENROL',
        'CLASS_VIEW',
        'DATA_EXPORT',
        'DATA_IMPORT',
        'GUARDIAN_MANAGE',
        'GUARDIAN_VIEW',
        'REPORT_CARD_VIEW',
        'STUDENT_ARCHIVE',
        'STUDENT_CREATE',
        'STUDENT_DOCUMENT_MANAGE',
        'STUDENT_DOCUMENT_VIEW',
        'STUDENT_PROMOTE',
        'STUDENT_UPDATE',
        'STUDENT_VIEW',
        'TRANSCRIPT_ISSUE'
       )
 WHERE r.code = 'REGISTRAR' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Admissions Officer: 10 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ADMISSION_APPLICATION_MANAGE',
        'ADMISSION_APPLICATION_VIEW',
        'ADMISSION_ENROL',
        'ANNOUNCEMENT_VIEW',
        'CLASS_VIEW',
        'FEES_VIEW',
        'GUARDIAN_MANAGE',
        'GUARDIAN_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'ADMISSIONS_OFFICER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Teacher: 17 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_MARK',
        'ATTENDANCE_VIEW',
        'CLASS_VIEW',
        'GRADE_EDIT_DRAFT',
        'GRADE_ENTER',
        'GRADE_SUBMIT',
        'HEALTH_ALERT_VIEW',
        'HR_LEAVE_REQUEST',
        'LIBRARY_VIEW',
        'MESSAGE_SEND',
        'PAYSLIP_VIEW_OWN',
        'REPORT_CARD_VIEW',
        'STUDENT_VIEW_OWN_CLASS',
        'SUBJECT_VIEW',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'TEACHER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Class Teacher: 19 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_MARK',
        'ATTENDANCE_VIEW',
        'CLASS_VIEW',
        'DISCIPLINE_VIEW',
        'GRADE_EDIT_DRAFT',
        'GRADE_ENTER',
        'GRADE_SUBMIT',
        'GUARDIAN_VIEW',
        'HEALTH_ALERT_VIEW',
        'HR_LEAVE_REQUEST',
        'MESSAGE_SEND',
        'PAYSLIP_VIEW_OWN',
        'REPORT_CARD_GENERATE',
        'REPORT_CARD_VIEW',
        'STUDENT_VIEW_OWN_CLASS',
        'SUBJECT_VIEW',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'CLASS_TEACHER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Head of Department: 20 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANALYTICS_ACADEMIC_VIEW',
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_MANAGE',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_VIEW',
        'CLASS_VIEW',
        'GRADE_EDIT_DRAFT',
        'GRADE_ENTER',
        'GRADE_REVIEW',
        'GRADE_SUBMIT',
        'HR_LEAVE_APPROVE',
        'HR_LEAVE_REQUEST',
        'MESSAGE_SEND',
        'PAYSLIP_VIEW_OWN',
        'REPORT_CARD_VIEW',
        'STUDENT_VIEW_OWN_CLASS',
        'SUBJECT_MANAGE',
        'SUBJECT_VIEW',
        'TEACHING_ASSIGNMENT_MANAGE',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'HEAD_OF_DEPARTMENT' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Bursar: 18 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACCOUNTING_REPORT_VIEW',
        'ACCOUNTING_VIEW',
        'ANALYTICS_FINANCE_VIEW',
        'DATA_EXPORT',
        'FEES_DISCOUNT',
        'FEES_STRUCTURE_MANAGE',
        'FEES_VIEW',
        'GUARDIAN_VIEW',
        'INVOICE_CANCEL',
        'INVOICE_CREATE',
        'MESSAGE_SEND',
        'PAYMENT_ALLOCATE',
        'PAYMENT_RECORD',
        'PAYMENT_REFUND',
        'RECEIPT_ISSUE',
        'RECONCILIATION_RESOLVE',
        'RECONCILIATION_VIEW',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'BURSAR' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Accountant: 13 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACCOUNTING_COA_MANAGE',
        'ACCOUNTING_JOURNAL_CREATE',
        'ACCOUNTING_REPORT_VIEW',
        'ACCOUNTING_VIEW',
        'ANALYTICS_FINANCE_VIEW',
        'ASSET_VIEW',
        'BUDGET_MANAGE',
        'DATA_EXPORT',
        'FEES_VIEW',
        'INVENTORY_VIEW',
        'RECONCILIATION_RESOLVE',
        'RECONCILIATION_VIEW',
        'TAX_RULE_MANAGE'
       )
 WHERE r.code = 'ACCOUNTANT' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Finance Manager: 19 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACCOUNTING_COA_MANAGE',
        'ACCOUNTING_JOURNAL_APPROVE',
        'ACCOUNTING_JOURNAL_CREATE',
        'ACCOUNTING_JOURNAL_POST',
        'ACCOUNTING_JOURNAL_REVERSE',
        'ACCOUNTING_PERIOD_CLOSE',
        'ACCOUNTING_REPORT_VIEW',
        'ACCOUNTING_VIEW',
        'ANALYTICS_FINANCE_VIEW',
        'AUDIT_LOG_VIEW',
        'BUDGET_MANAGE',
        'DATA_EXPORT',
        'FEES_VIEW',
        'FEES_WAIVE',
        'PAYMENT_REFUND_APPROVE',
        'PAYROLL_VIEW',
        'RECONCILIATION_RESOLVE',
        'RECONCILIATION_VIEW',
        'TAX_RULE_MANAGE'
       )
 WHERE r.code = 'FINANCE_MANAGER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- HR Manager: 15 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'DATA_EXPORT',
        'HR_CONTRACT_MANAGE',
        'HR_DISCIPLINARY_MANAGE',
        'HR_LEAVE_APPROVE',
        'HR_PERFORMANCE_MANAGE',
        'HR_SALARY_MANAGE',
        'HR_SALARY_VIEW',
        'HR_STAFF_MANAGE',
        'HR_STAFF_VIEW',
        'MESSAGE_SEND',
        'PAYROLL_VIEW',
        'STAFF_ATTENDANCE_VIEW',
        'USER_INVITE',
        'USER_VIEW'
       )
 WHERE r.code = 'HR_MANAGER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Payroll Officer: 7 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'HR_SALARY_VIEW',
        'HR_STAFF_VIEW',
        'PAYROLL_PREPARE',
        'PAYROLL_STATUTORY_MANAGE',
        'PAYROLL_VIEW',
        'PAYSLIP_VIEW_ALL',
        'STAFF_ATTENDANCE_VIEW'
       )
 WHERE r.code = 'PAYROLL_OFFICER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Librarian: 6 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'LIBRARY_CIRCULATE',
        'LIBRARY_MANAGE',
        'LIBRARY_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'LIBRARIAN' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Nurse / Health Officer: 6 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'GUARDIAN_VIEW',
        'HEALTH_ALERT_VIEW',
        'HEALTH_RECORD_MANAGE',
        'HEALTH_RECORD_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'NURSE' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Counsellor: 6 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'COUNSELLING_MANAGE',
        'COUNSELLING_VIEW',
        'DISCIPLINE_VIEW',
        'GUARDIAN_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'COUNSELLOR' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Transport Manager: 6 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ASSET_VIEW',
        'GUARDIAN_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW',
        'TRANSPORT_MANAGE',
        'TRANSPORT_VIEW'
       )
 WHERE r.code = 'TRANSPORT_MANAGER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Hostel Manager: 7 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'DISCIPLINE_VIEW',
        'GUARDIAN_VIEW',
        'HEALTH_ALERT_VIEW',
        'HOSTEL_MANAGE',
        'HOSTEL_VIEW',
        'MESSAGE_SEND',
        'STUDENT_VIEW'
       )
 WHERE r.code = 'HOSTEL_MANAGER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Storekeeper: 4 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ASSET_VIEW',
        'INVENTORY_MANAGE',
        'INVENTORY_VIEW',
        'PROCUREMENT_RECEIVE'
       )
 WHERE r.code = 'STOREKEEPER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Procurement Officer: 6 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ACCOUNTING_VIEW',
        'ASSET_VIEW',
        'INVENTORY_VIEW',
        'PROCUREMENT_ORDER',
        'PROCUREMENT_RECEIVE',
        'PROCUREMENT_REQUEST'
       )
 WHERE r.code = 'PROCUREMENT_OFFICER' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- ICT Administrator: 11 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'AUDIT_LOG_VIEW',
        'DATA_IMPORT',
        'NOTIFICATION_FAILURE_VIEW',
        'NOTIFICATION_SETTINGS_MANAGE',
        'ROLE_VIEW',
        'SESSION_REVOKE',
        'TENANT_API_KEY_MANAGE',
        'TENANT_INTEGRATION_MANAGE',
        'TENANT_SETTINGS_VIEW',
        'USER_INVITE',
        'USER_VIEW'
       )
 WHERE r.code = 'ICT_ADMINISTRATOR' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Student: 7 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_VIEW',
        'LIBRARY_VIEW',
        'MESSAGE_SEND',
        'REPORT_CARD_VIEW',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'STUDENT' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;

-- Parent / Guardian: 9 permissions
INSERT INTO identity.role_permission (role_id, permission_id)
SELECT r.id, p.id
  FROM identity.role r
  JOIN identity.permission p ON p.code IN (
        'ANNOUNCEMENT_VIEW',
        'ASSESSMENT_VIEW',
        'ATTENDANCE_VIEW',
        'FEES_VIEW',
        'HEALTH_ALERT_VIEW',
        'LIBRARY_VIEW',
        'MESSAGE_SEND',
        'REPORT_CARD_VIEW',
        'TIMETABLE_VIEW'
       )
 WHERE r.code = 'GUARDIAN' AND r.tenant_id IS NULL
ON CONFLICT DO NOTHING;
